# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "test_scenarios",
    actual = "//score/kvs/rust_kvs/tests/test_scenarios",
    deprecation = "//score/kvs/tests/test_scenarios/rust:test_scenarios has moved to //score/kvs/rust_kvs/tests/test_scenarios.",
    visibility = ["//visibility:public"],
)
